[package]
name = "tui-pwsafe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-pwsafe = "0.0.7"
tui = "0.19"
crossterm = "0.27.0"
unicode-width = "0.1.11"
arboard = "3.3.2"